apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: hoobs
  name: hoobs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hoobs
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hoobs
    spec:
      containers:
        - env:
            - name: PGID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: TZ
              value: Europe/Amsterdam
          image: hoobs/hoobs
          name: hoobs
          ports:
            - containerPort: 80
            - containerPort: 51826
          resources: {}
          volumeMounts:
            - mountPath: /hoobs
              name: hoobs-claim0
      restartPolicy: Always
      volumes:
        - name: hoobs-claim0
          persistentVolumeClaim:
            claimName: hoobs-claim0
status: {}
